apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-icsi
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-icsi
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-icsi
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-icsi
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-icsi
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-qfxe-tenant/rhtap-demo-app/hacbs-test-project-icsi@sha256:5b66fb2b74fb5146c7820c59dd5eb28c335304655f5477cc1c45b70a89c27386
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
